version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: cineticket-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cineticket # VeritabanÄ±mÄ±zÄ±n adÄ±
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # ğŸ‘‡ Ä°ÅTE O SÄ°HÄ°RLÄ° SATIR:
      # migrations klasÃ¶rÃ¼nÃ¼ konteynerin iÃ§ine "initdb" klasÃ¶rÃ¼ne kopyalÄ±yoruz.
      # Postgres ilk aÃ§Ä±lÄ±ÅŸta buradaki .sql dosyalarÄ±nÄ± sÄ±rayla Ã§alÄ±ÅŸtÄ±rÄ±r!
      - ./migrations:/docker-entrypoint-initdb.d
    restart: always

volumes:
  postgres_data: